import ast
import dataclasses
import re
from pathlib import Path

from review import vocab

REPO_ROOT = Path(__file__).resolve().parents[2]

#: The lineage key a fixture ledger's events fall under when none of them
#: declares an id (brief `keyed-lineage`): the legacy positional ordinal,
#: as a decimal string, counted by `lineage_closed` markers. A fixture that
#: records no closure is lineage "1", which is what almost every test here
#: builds — and reading it under this key is the same read those tests made
#: before the lineage was keyed. `LINEAGE_AFTER(n)` names the key after `n`
#: recorded closures, for the few that close and keep going.
LINEAGE = "1"


def LINEAGE_AFTER(closures: int) -> str:
    """The legacy positional key after `closures` recorded closures."""
    return str(closures + 1)


@dataclasses.dataclass
class CliArgs:
    """The argparse namespace the `ledger` subcommands read, for driving
    `cmd_ledger_add` / `cmd_ledger_report` directly over an in-memory ledger
    (the product function `main` dispatches to, minus the filesystem)."""
    envelope: str = ""
    round: int | None = None
    tokens: int | None = None
    against: str | None = None
    format: str | None = "json"
    ledger_dir: str | None = None


#: The evaluation-scope grammar, and the AUTHORITY it is closed against.
#:
#: Round-3 F1 was the third finding on this one anchor: round 1 put
#: definition-time expressions in the defining scope, round 2 gave deferred
#: bodies their own, and round 3 found PEP 695 type parameters — dropped
#: entirely — and lazy type aliases attributed to `<module>`. Three
#: instances of one shape, which is the hunting signature the
#: boundary-authority terminator exists to end: the domain "every execution
#: container" was closed against nothing but the visitor methods someone
#: had written.
#:
#: So the domain is now declared closed RELATIVE TO A STATED AUTHORITY: the
#: `ast` grammar of the running interpreter — generated by CPython, not by
#: this repository, and gated by
#: `test_the_scope_grammar_covers_the_ast_grammar`. Every concrete node
#: type is classified exactly once, and for a scope-introducing node EVERY
#: field is routed by name. A node type or field the grammar grows — a
#: future interpreter's new lazy scope — fails that gate until someone
#: decides it, instead of being swept up by a generic traversal. There are
#: no prefix rules and no default arm; that absence IS the fix.
#:
#: Treatments:
#:   skip                a name or flag, not an evaluable child
#:   current             evaluates in the scope now on the stack
#:   own_scope           the function's own body (pushes the function name)
#:   lambda_scope        deferred, unnamed: `<lambda>`
#:   genexp_elt          deferred until a consumer iterates: `<genexpr>`
#:   genexp_generators   outermost iterable eager in the creating scope,
#:                       every other iterable, target and filter deferred
#:   annotation          a PEP 695 lazy scope: `<annotation>`, ALWAYS —
#:                       `from __future__ import annotations` governs legacy
#:                       annotations and has no bearing on these
#:   legacy_annotation   `<annotation>`, unless the module stringifies
SCOPE_RULES = {
    "FunctionDef": {"name": "skip", "type_comment": "skip",
                    "decorator_list": "current", "args": "current",
                    "type_params": "current",
                    "returns": "legacy_annotation", "body": "own_scope"},
    "AsyncFunctionDef": {"name": "skip", "type_comment": "skip",
                         "decorator_list": "current", "args": "current",
                         "type_params": "current",
                         "returns": "legacy_annotation",
                         "body": "own_scope"},
    "Lambda": {"args": "current", "body": "lambda_scope"},
    "GeneratorExp": {"elt": "genexp_elt",
                     "generators": "genexp_generators"},
    # A class body EXECUTES at the class statement, so it is the current
    # scope; only its type parameters are lazy.
    "ClassDef": {"name": "skip", "bases": "current", "keywords": "current",
                 "decorator_list": "current", "type_params": "current",
                 "body": "current"},
    "TypeAlias": {"name": "current", "type_params": "current",
                  "value": "annotation"},
    "TypeVar": {"name": "skip", "bound": "annotation",
                "default_value": "annotation"},
    "ParamSpec": {"name": "skip", "default_value": "annotation"},
    "TypeVarTuple": {"name": "skip", "default_value": "annotation"},
    "AnnAssign": {"target": "current", "annotation": "legacy_annotation",
                  "value": "current", "simple": "skip"},
    "arg": {"arg": "skip", "annotation": "legacy_annotation",
            "type_comment": "skip"},
}

#: Every other concrete node type: its children evaluate in the scope now
#: on the stack. Enumerated, never defaulted — a new node type is
#: unclassified until someone rules on it. `arguments` and `comprehension`
#: are here on purpose: their evaluable children are defaults and iterables
#: that run where they are written, while the parts that are NOT
#: (`arg` annotations, a generator's deferred iterables) are routed by the
#: rules above.
TRANSPARENT_NODES = frozenset({
    "Add", "And", "Assert", "Assign",
    "AsyncFor", "AsyncWith", "Attribute", "AugAssign",
    "AugLoad", "AugStore", "Await", "BinOp",
    "BitAnd", "BitOr", "BitXor", "BoolOp",
    "Break", "Call", "Compare", "Constant",
    "Continue", "Del", "Delete", "Dict",
    "DictComp", "Div", "Eq", "ExceptHandler",
    "Expr", "Expression", "ExtSlice", "FloorDiv",
    "For", "FormattedValue", "FunctionType", "Global",
    "Gt", "GtE", "If", "IfExp",
    "Import", "ImportFrom", "In", "Index",
    "Interactive", "Interpolation", "Invert", "Is",
    "IsNot", "JoinedStr", "LShift", "List",
    "ListComp", "Load", "Lt", "LtE",
    "MatMult", "Match", "MatchAs", "MatchClass",
    "MatchMapping", "MatchOr", "MatchSequence", "MatchSingleton",
    "MatchStar", "MatchValue", "Mod", "Module",
    "Mult", "Name", "NamedExpr", "Nonlocal",
    "Not", "NotEq", "NotIn", "Or",
    "Param", "Pass", "Pow", "RShift",
    "Raise", "Return", "Set", "SetComp",
    "Slice", "Starred", "Store", "Sub",
    "Subscript", "Suite", "TemplateStr", "Try",
    "TryStar", "Tuple", "TypeIgnore", "UAdd",
    "USub", "UnaryOp", "While", "With",
    "Yield", "YieldFrom", "alias", "arguments",
    "comprehension", "keyword", "match_case", "withitem",
    # The ASDL base types. They are never instantiated, so they carry no
    # children of their own — but they ARE subclasses of `ast.AST`, and
    # the derivation enumerates every subclass rather than guessing at
    # leaves, so each is decided here like everything else.
    "boolop", "cmpop", "excepthandler", "expr",
    "expr_context", "mod", "operator", "pattern",
    "slice", "stmt", "type_ignore", "type_param",
    "unaryop",
})


def ast_grammar_nodes(module=ast) -> frozenset:
    """The authority: every node type in the `ast` grammar — EVERY subclass
    of `ast.AST`, abstract bases included, never the leaves of the class
    tree.

    Round-4 F1 rejected an earlier form of this authority for excluding
    grammars the package promised to support, and it was right to: the
    routing table was written for one interpreter while `requires-python`
    advertised four. That is settled at the claim rather than the
    mechanism — the package now requires the interpreter it is gated on
    (decided 2026-08-26 by the user, after CI evidence that `>=3.11` had
    never been true: six PEP 701 f-string sites mean the package does not
    IMPORT on 3.11, through two publications). One supported interpreter
    means the grammar of the running one IS the supported domain, and the
    exclusion the finding named excludes nothing.

    Leaf-ness is deliberately not used as the concreteness test. Before
    3.12 `ast.Num` and friends are subclasses of `Constant`, so a leaf
    derivation drops `Constant` and grows five unclassified node types;
    that seam is gone with the older grammars, but enumerating every
    subclass has no such seam at any version and costs nothing.
    """
    found = set()

    def walk(cls):
        for sub in cls.__subclasses__():
            if sub.__module__.split(".")[0] == module.__name__.split(".")[0]:
                found.add(sub.__name__)
                walk(sub)

    walk(module.AST)
    return frozenset(found)


def grammar_fields(name, module=ast):
    """The fields of one node type, or None where the grammar has no such
    node."""
    node = getattr(module, name, None)
    return None if node is None else tuple(node._fields)


def grammar_problems(nodes, fields_of) -> list:
    """Everything wrong with a (grammar, scope-table) pair, as strings
    naming the node or field — pure, so a probe can run it against a
    modified grammar without going through the gate.

    Every node type is classified exactly once and every field of every
    scope-introducing node is routed by name. No prefix rule, no default
    arm: that absence is what makes a new lazy scope fail here rather than
    reach a reviewer.
    """
    problems = []
    classified = set(SCOPE_RULES) | set(TRANSPARENT_NODES)
    for name in sorted(set(SCOPE_RULES) & set(TRANSPARENT_NODES)):
        problems.append(f"{name}: both scope-introducing and transparent")
    for name in sorted(nodes - classified):
        problems.append(f"{name}: in the grammar and classified nowhere")
    for name in sorted(classified - nodes):
        problems.append(f"{name}: classified but absent from the grammar")
    for name, rule in sorted(SCOPE_RULES.items()):
        fields = fields_of(name)
        if fields is None:
            problems.append(f"{name}: a scope rule for a node the grammar "
                            f"does not have")
            continue
        for field in sorted(set(fields) - set(rule)):
            problems.append(f"{name}.{field}: no scope rule routes it")
        for field in sorted(set(rule) - set(fields)):
            problems.append(f"{name}.{field}: routed, but not a field of "
                            f"the grammar")
    return problems


def stamped_parse_sites(module: str, source: str) -> set:
    """Every site in `source` that calls a stamped-envelope parser, as
    `(module, scope)` pairs — THE scanner, singular (lineage 8).

    Both halves of the reader-boundary gate walk their universes through
    this one function — the travelling half over `production_modules()`,
    the workbench half over the inventory-derived stays modules — and the
    synthetic-module tests probe its call domain directly, so the domain
    has a single owner. Until lineage 8 the workbench half re-implemented
    the walk and had silently lost the import-alias arm: an aliased parse
    in a stays module was invisible to the gate that existed to see it.

    Scopes follow EVALUATION time, not syntax: a scope is credited with
    the code it RUNS, never with code it merely creates or declares. The
    routing lives in `SCOPE_RULES` above, closed against the `ast` grammar
    — read that comment for the authority and the treatments.

    Named scopes: a function's own name for its body, `<lambda>`,
    `<genexpr>`, `<annotation>` for every lazy annotation scope (legacy
    annotations under PEP 649 and PEP 695 type parameters and type-alias
    values alike — one seam for every lazy annotation scope, which is
    also what kept the attribution honest while the package still claimed
    older runtimes), and
    `<module>` for code that runs at import.

    Two stated over-approximations, conservative by design — a reader can
    be over-reported, never lost: a function-local variable annotation is
    reported under `<annotation>` although no supported runtime evaluates
    it, and a stringified-annotation module still reports its PEP 695
    scopes, which is correct (the future import does not defer those).

    The call forms admitted: bare calls, attribute calls
    (`wire.parse_request`), and calls through an import alias
    (`from .wire import parse_request as pr`). The declared bound, stated
    rather than implied: a parse reached by dynamic dispatch —
    `getattr(wire, name)(...)` — is invisible to any structural walk.
    """
    tree = ast.parse(source)
    stringified = any(
        isinstance(node, ast.ImportFrom) and node.module == "__future__"
        and any(alias.name == "annotations" for alias in node.names)
        for node in tree.body)
    # Import aliases first: a renamed import is the same call.
    aliases = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for name in node.names:
                if name.name in vocab.STAMPED_PARSE_CALLS and name.asname:
                    aliases[name.asname] = name.name
    found = set()
    stack = []

    def visit(node):
        if isinstance(node, ast.Call):
            func = node.func
            name = (func.attr if isinstance(func, ast.Attribute)
                    else getattr(func, "id", None))
            if aliases.get(name, name) in vocab.STAMPED_PARSE_CALLS:
                found.add((module, stack[-1] if stack else "<module>"))
        rule = SCOPE_RULES.get(type(node).__name__)
        if rule is None:
            for child in ast.iter_child_nodes(node):
                visit(child)
            return
        for field, treatment in rule.items():
            route(node, field, treatment)

    def descend(value):
        if isinstance(value, ast.AST):
            visit(value)
        elif isinstance(value, list):
            for item in value:
                descend(item)

    def scoped(name, value):
        stack.append(name)
        descend(value)
        stack.pop()

    def route(node, field, treatment):
        value = getattr(node, field, None)
        if value is None or treatment == "skip":
            return
        if treatment == "current":
            descend(value)
        elif treatment == "own_scope":
            scoped(node.name, value)
        elif treatment == "lambda_scope":
            scoped("<lambda>", value)
        elif treatment == "genexp_elt":
            scoped("<genexpr>", value)
        elif treatment == "genexp_generators":
            # Only the outermost iterable is evaluated at creation.
            descend(value[0].iter)
            stack.append("<genexpr>")
            for position, comp in enumerate(value):
                descend(comp.target)
                if position:
                    descend(comp.iter)
                descend(comp.ifs)
            stack.pop()
        elif treatment == "annotation":
            scoped("<annotation>", value)
        elif treatment == "legacy_annotation":
            if not stringified:
                scoped("<annotation>", value)
        else:
            raise AssertionError(f"unknown treatment {treatment!r}")

    visit(tree)
    return found


def spec_path() -> Path | None:
    """The shipped specification, in whichever tree this suite is running in.

    The same file has two paths. In the workbench it is `public/docs/design.md`,
    because `public/` is the boundary marking what travels; in an extracted
    candidate the prefix is stripped and it is `docs/design.md`. A travelling
    test that hardcodes either one passes in one tree and errors in the other,
    which is how the candidate's standalone suite caught this test the first
    time it ran.

    Returns None where neither exists, so a caller can skip rather than fail:
    a suite running somewhere the spec was not shipped has nothing to say
    about the spec, and that is different from the spec being wrong.
    """
    for rel in ("public/docs/design.md", "docs/design.md"):
        candidate = REPO_ROOT / rel
        if candidate.is_file():
            return candidate
    return None


def public_path(*names: str) -> Path | None:
    """A shipped file by its candidate-root name, in whichever tree this
    suite runs in: `public/<name>` in the workbench, `<name>` in an
    extracted candidate. None where neither exists (sweep F13: the README
    is now a parity fixture and has the same two paths the spec has)."""
    for name in names:
        for rel in (f"public/{name}", name):
            candidate = REPO_ROOT / rel
            if candidate.is_file():
                return candidate
    return None


#: ONE version component of the declared interpreter interval, in the ONE
#: spelling every reader of `project.requires-python` admits: `0`, or a
#: non-zero ASCII digit followed by at most three more ASCII digits.
#:
#: Two rounds put the two halves of that sentence here. CANONICAL ASCII
#: (lineage Lf45b38923c round 3 F1): Python's `\d` is the Unicode `Nd`
#: category, so `\d+` admitted `٣` and `014`, each of which a reader
#: interpolates into a Python integer literal and each of which is a
#: SyntaxError. BOUNDED at four digits (lineage La146cf464d round 1 F4): a
#: canonical decimal of unbounded length is still not a literal everywhere
#: — CPython's default integer-string conversion limit is 4,300 digits, and
#: a component of 4,301 `1`s was rendered, checked clean and published. A
#: version component is a small integer; 9999 is four orders of magnitude
#: past any released Python and three below that limit, so the bound closes
#: the CLASS instead of chasing an instance of a limit that is configurable
#: per process and per version.
INTERVAL_COMPONENT = r"(0|[1-9][0-9]{0,3})"

_DECLARED_INTERVAL = re.compile(
    ">=" + INTERVAL_COMPONENT + r"\." + INTERVAL_COMPONENT
    + ",<" + INTERVAL_COMPONENT + r"\." + INTERVAL_COMPONENT)

#: The refusal, in the one wording every reader prints. It names the RULE,
#: not just the value: an operator holding a valid-looking `>=X.Y,<X.Z`
#: needs to be told which property of it was wrong.
INTERVAL_SHAPE = ("the '>=X.Y,<X.Z' shape in canonical ASCII decimals of "
                  "at most 4 digits that the interval gate admits")


def declared_interval(spec):
    """`project.requires-python` as `((floor_major, floor_minor),
    (below_major, below_minor))`, or `ValueError` naming what was wrong.

    THE single authority for that value's spelling, for every reader that
    travels with this package. It exists because there were three, held to
    one shape by prose alone: this package's interpreter-floor check and
    its packaging-interval gate each parsed the value with a regex of its
    own — one `re.fullmatch` over Unicode `\\d` with optional whitespace
    and an optional third component, one `re.search` over a SUBSTRING — so
    a spelling one admitted another refused, and neither was the bounded
    canonical grammar the generator downstream requires.

    The match is over the WHOLE value (round 2 F1: a multiline TOML string
    carrying one admitted line beside another was accepted line by line and
    rendered invalid shell), and each component is `INTERVAL_COMPONENT`.

    A THIRD reader lives outside this package, in the workbench that
    develops it: a generator that embeds this interval in a shell snippet.
    It holds the same grammar as embedded Python rather than importing this
    one — it resolves its own root and must render from any tree, including
    the scratch roots its own suite builds, where this package is not
    importable — and the workbench holds the two equal row by row over a
    single partition table. Nothing in the published tree depends on that;
    it is recorded here so a change to this grammar is known to have a
    reader it cannot see.
    """
    if not isinstance(spec, str):
        raise ValueError(
            f"requires-python is {spec!r}, which is not a string, so it is "
            f"not {INTERVAL_SHAPE}")
    found = _DECLARED_INTERVAL.fullmatch(spec)
    if found is None:
        raise ValueError(
            f"requires-python is {spec!r}, not {INTERVAL_SHAPE}")
    floor_major, floor_minor, below_major, below_minor = found.groups()
    return ((int(floor_major), int(floor_minor)),
            (int(below_major), int(below_minor)))


def cli_report(test, ledger, cfg):
    """`ledger report` driven over a supplied ledger — the product function
    `main` dispatches to, with an in-memory backend so the check holds in a
    read-only sandbox. Shared by the corpus report tests (stay behind) and
    the gate-manifest metric tests (travel)."""
    import contextlib
    import io
    import json
    import unittest.mock
    from review.cli import cmd_ledger_report
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        with unittest.mock.patch("review.cli._ledger", return_value=ledger):
            code = cmd_ledger_report(CliArgs(format="json"), cfg)
    test.assertEqual(code, 0)
    return json.loads(buf.getvalue())
